CREATE TABLE IF NOT EXISTS genre (
    genre_id BIGINT PRIMARY KEY,
    name     VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS age_rating (
    age_rating_id BIGINT PRIMARY KEY,
    name          VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(255) NOT NULL UNIQUE,
    login     VARCHAR(255) NOT NULL UNIQUE,
    name      VARCHAR(255) NOT NULL,
    birthday  DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS film (
    film_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    description    VARCHAR(200),
    release_date   DATE         NOT NULL,
    duration       INTEGER      NOT NULL,
    age_rating_id  BIGINT       NOT NULL,
    CONSTRAINT fk_film_age_rating
        FOREIGN KEY (age_rating_id) REFERENCES age_rating (age_rating_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT pk_film_genre PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_film_genre_film
        FOREIGN KEY (film_id) REFERENCES film (film_id) ON DELETE CASCADE,
    CONSTRAINT fk_film_genre_genre
        FOREIGN KEY (genre_id) REFERENCES genre (genre_id)
);

CREATE TABLE IF NOT EXISTS film_rating (
    film_rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id        BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    CONSTRAINT uk_film_rating UNIQUE (film_id, user_id),
    CONSTRAINT fk_film_rating_film
        FOREIGN KEY (film_id) REFERENCES film (film_id) ON DELETE CASCADE,
    CONSTRAINT fk_film_rating_user
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friendship_request (
    friendship_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_id          BIGINT       NOT NULL,
    receiver_id           BIGINT       NOT NULL,
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP,
    status                VARCHAR(20)  NOT NULL,
    CONSTRAINT uk_friendship_request UNIQUE (initiator_id, receiver_id),
    CONSTRAINT fk_friendship_request_initiator
        FOREIGN KEY (initiator_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_friendship_request_receiver
        FOREIGN KEY (receiver_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT ck_friendship_request_not_self
        CHECK (initiator_id <> receiver_id),
    CONSTRAINT ck_friendship_request_status
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED'))
);
